name: PR check
on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
jobs:
  pr_check:
    runs-on: ubuntu-latest
  steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
    - name: Print PR Branch Name
      run: |
        echo “PR Check running for branch: ${{ GitHub.head_ref }}”